import { afterEach, expect, it } from 'vitest';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import type { StudyState } from '../src/domain/types';
import { createBackup, replaceRestore, serializeBackup } from '../src/backup/backup';
import { QbtDatabase, toQuestionRecord } from '../src/data/db';
import { createAttempt } from '../src/engine/attemptFactory';
import { createSessionRecord, endSessionRecord } from '../src/engine/sessionFactory';
import { seedQuestions } from '../src/data/seed';
const dbs:QbtDatabase[]=[]; const evidence=resolve(process.env.EVIDENCE_DIR??'../evidence','AC-08'); const makeDb=(n:string)=>{const d=new QbtDatabase(n);dbs.push(d);return d;};
function state(q:string,r:string):StudyState{return{questionId:q,revisionId:r,dueAt:'2026-09-20T00:00:00.000Z',intervalDays:1,easeFactor:2.5,repetitions:1,lapses:0,bestBuzzIndex:1,bestBuzzRatio:0.25,bestResponseTimeMs:250,correctCount:1,attemptCount:1,streak:1};}
async function seed(db:QbtDatabase,p:string){const q=seedQuestions[p==='source'?0:1]!;const s=createSessionRecord({sessionId:`${p}-session`,mode:'normal',startedAt:'2026-09-19T00:00:00.000Z',targetQuestionCount:1});const a=createAttempt({attemptId:`${p}-attempt`,question:q,sessionId:s.sessionId,mode:'normal',outcome:'correct',judge:{kind:'canonical',isCorrect:true,normalizedSubmitted:q.answers.primaryAnswer.text,matchedAnswer:q.answers.primaryAnswer.text},submittedAnswer:q.answers.primaryAnswer.text,startedAt:'2026-09-19T00:00:01.000Z',completedAt:'2026-09-19T00:00:02.000Z',buzz:{buzzIndex:1,totalGraphemeCount:q.derived.graphemeCount,buzzRatio:1/q.derived.graphemeCount,visibleText:q.prompt.slice(0,1),buzzTimeMs:100,buzzAtMs:100},responseTimeMs:250});await db.questions.add(toQuestionRecord(q));await db.attempts.add(a);await db.studyStates.add(state(q.questionId,q.revisionId));await db.sessions.add(endSessionRecord(s,'completed',a.completedAt,{consumedQuestionCount:1}));await db.settings.add({key:`${p}-setting`,value:p});}
afterEach(async()=>{await Promise.all(dbs.splice(0).map(async d=>{d.close();await d.delete();}));});
it('AC-08 Replace Restore',async()=>{await mkdir(evidence,{recursive:true});const source=makeDb('qbt-rv-ac08-source'),target=makeDb('qbt-rv-ac08-target');await seed(source,'source');await seed(target,'old');const incoming=await createBackup(source),pre=await createBackup(target);await replaceRestore(incoming,target);const post=await createBackup(target);const qkeys=new Set(post.data.questions.map(q=>`${q.questionId}::${q.revisionId}`));const sessions=new Set(post.data.sessions.map(s=>s.sessionId));const integrity=post.data.attempts.every(a=>qkeys.has(`${a.questionId}::${a.revisionId}`)&&sessions.has(a.sessionId))&&post.data.studyStates.every(s=>qkeys.has(`${s.questionId}::${s.revisionId}`));const pass=isDeepStrictEqual(post.data,incoming.data)&&integrity;await writeFile(resolve(evidence,'ac08-backup.json'),serializeBackup(incoming));await writeFile(resolve(evidence,'ac08-pre-restore.json'),serializeBackup(pre));await writeFile(resolve(evidence,'ac08-post-restore.json'),serializeBackup(post));await writeFile(resolve(evidence,'ac08-integrity-report.json'),JSON.stringify({ac:'AC-08',pass,integrity,counts:Object.fromEntries(Object.entries(post.data).map(([k,v])=>[k,(v as unknown[]).length]))},null,2)+'\n');expect(pass).toBe(true);});
