import { afterEach, expect, it } from 'vitest';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createBackup, parseBackupJson, replaceRestore } from '../src/backup/backup';
import { QbtDatabase, toQuestionRecord } from '../src/data/db';
import { createAttempt } from '../src/engine/attemptFactory';
import { createSessionRecord, endSessionRecord } from '../src/engine/sessionFactory';
import { seedQuestions } from '../src/data/seed';
const dbs:QbtDatabase[]=[];const evidence=resolve(process.env.EVIDENCE_DIR??'../evidence','AC-09');const mk=(n:string)=>{const d=new QbtDatabase(n);dbs.push(d);return d;};
async function seed(db:QbtDatabase,p:string){const q=seedQuestions[0]!;const s=createSessionRecord({sessionId:`${p}-s`,mode:'normal',startedAt:'2026-09-19T00:00:00.000Z',targetQuestionCount:1});const a=createAttempt({attemptId:`${p}-a`,question:q,sessionId:s.sessionId,mode:'normal',outcome:'correct',judge:{kind:'canonical',isCorrect:true,normalizedSubmitted:q.answers.primaryAnswer.text,matchedAnswer:q.answers.primaryAnswer.text},submittedAnswer:q.answers.primaryAnswer.text,startedAt:'2026-09-19T00:00:01.000Z',completedAt:'2026-09-19T00:00:02.000Z',buzz:{buzzIndex:1,totalGraphemeCount:q.derived.graphemeCount,buzzRatio:1/q.derived.graphemeCount,visibleText:q.prompt.slice(0,1),buzzTimeMs:100,buzzAtMs:100},responseTimeMs:200});await db.questions.add(toQuestionRecord(q));await db.attempts.add(a);await db.sessions.add(endSessionRecord(s,'completed',a.completedAt,{consumedQuestionCount:1}));}
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
afterEach(async()=>{await Promise.all(dbs.splice(0).map(async d=>{d.close();await d.delete();}));});
it('AC-09 Corrupted Backup Rejection',async()=>{await mkdir(evidence,{recursive:true});const source=mk('qbt-rv-ac09-source');await seed(source,'source');const valid=await createBackup(source);const cases:Array<{name:string,input:unknown|string,useJson?:boolean}>=[{name:'invalid-json',input:'{not-json',useJson:true},{name:'unknown-format',input:{...clone(valid),format:'other'}},{name:'newer-version',input:{...clone(valid),version:99}},{name:'missing-fields',input:(()=>{const x:any=clone(valid);delete x.data.settings;return x;})()},{name:'invalid-types',input:(()=>{const x:any=clone(valid);x.data.attempts='not-array';return x;})()},{name:'broken-references',input:(()=>{const x:any=clone(valid);x.data.attempts[0].questionId='missing-question';x.data.attempts[0].revisionId='r404';return x;})()}];const results:any[]=[];for(const c of cases){const target=mk(`qbt-rv-ac09-${c.name}`);await seed(target,'existing');const before=await createBackup(target);let rejected=false,error:string|null=null;try{if(c.useJson){parseBackupJson(c.input as string);}else{await replaceRestore(c.input,target);}}catch(e){rejected=true;error=e instanceof Error?e.message:String(e);}const after=await createBackup(target);const unchanged=JSON.stringify(before.data)===JSON.stringify(after.data);let usable=true;try{await target.questions.count();await target.attempts.count();}catch{usable=false;}results.push({case:c.name,rejected,error,dbUnchanged:unchanged,appUsable:usable,pass:rejected&&unchanged&&usable});}const pass=results.every(r=>r.pass===true);await writeFile(resolve(evidence,'ac09-invalid-input-results.json'),JSON.stringify({ac:'AC-09',pass,results},null,2)+'\n');expect(pass).toBe(true);});
